apiVersion: v1
kind: Pod
metadata:
  name: intro-pod
  namespace: homework
spec:
  containers:
  - name: nginx-container
    image: nginx:stable
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: intro-workdir
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","rm /homework/index.html"]
  initContainers:
  - name: init-container
    image: busybox:stable
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - https://ya.ru
    volumeMounts:
    - name: intro-workdir
      mountPath: "/init"
  dnsPolicy: Default
  volumes:
  - name: intro-workdir
    emptyDir: {}