apiVersion: apps/v1
kind: Deployment
metadata:
  name: controllers-pod
  namespace: homework
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      nodeSelector:
        homework: "true"
      initContainers:
      - name: init-container
        image: busybox:stable
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://example.com
        volumeMounts:
        - name: intro-workdir
          mountPath: "/init"
      dnsPolicy: Default
      containers:
      - name: nginx-container 
        image: nginx:stable
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: intro-workdir
          mountPath: /usr/share/nginx/html
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","rm /homework/index.html"]
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
        command: ["/bin/sh", "-c"]
        args:
        - |
          sed -i 's/server_name localhost;/server_name _;/g' /etc/nginx/conf.d/default.conf
          nginx -g 'daemon off;'
      volumes:
      - name: intro-workdir
        emptyDir: {}
      restartPolicy: Always
