apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:64537
  name: kubernetes
- cluster:
    certificate-authority: /Users/nickolayfilippov/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Mon, 17 Jun 2024 11:09:08 MSK
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://127.0.0.1:64537
  name: minikube
contexts:
- context:
    cluster: kubernetes
    namespace: homework
    user: cd
  name: cd@kubernetes
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 17 Jun 2024 11:09:08 MSK
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: cd
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjRreElEdWo4SmROVVpkaXJzVzRZZFlrNnQ2eV92YjlEV0ljTkwtcjF6WUEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzE4Njk3OTUzLCJpYXQiOjE3MTg2MTE1NTMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6IjdmN2ZiN2UyLTA0NTAtNDlkMS05ZTFkLTE5ZjU0ZDMxNGU1ZCJ9fSwibmJmIjoxNzE4NjExNTUzLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aG9tZXdvcms6Y2QifQ.X2icdrOu2aHauBtDszPy2vbukAFUgNPaDCOI7VeXtDcqxNXt5a-aTVE6ROY661wx8FKScF3lKtxwX4v10lqrJo_6_UBA2TKnPl9JpETDraBIF3YsIZClXPnEXv_NCzFFJcDY6stDCnhZ8mF21sKJOFWexIslqxCEX3HfUI329k9yc1w582S3hN147ArODGWXjNc0mxFO-i2gZqX04on5eU6ClHo7m2TcH4fIpkkVoqcmChhYT7dh42q1jzIzgv_XesINgt3wnoTnhGA1yrRBHa15xemv_W9UL4BA0Fd2j_tdvY8RdN6h4m3eGtxAXmbAorxaHjSMXhLClWAuiZGLuA
- name: minikube
  user:
    client-certificate: /Users/nickolayfilippov/.minikube/profiles/minikube/client.crt
    client-key: /Users/nickolayfilippov/.minikube/profiles/minikube/client.key
