apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: homework
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: ClusterIP